name: CI/CD Pipeline for Weather App

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t weather-backend ./backend

      - name: Run Docker container
        run: docker run -d -p 5000:5000 weather-backend
